#!/bin/bash

echo "GitHub Pages Setup Script"
echo "========================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. First, authenticate with GitHub CLI:"
echo "   gh auth login"
echo ""
echo "2. After authentication, create the repository:"
echo "   gh repo create jasontrost.github.io --public --source=. --remote=origin --push"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to https://github.com/jasontrost/jasontrost.github.io/settings/pages"
echo "   - Under 'Source', select 'Deploy from a branch'"
echo "   - Choose 'main' branch and '/ (root)' folder"
echo "   - Click 'Save'"
echo ""
echo "4. Your site will be available at: https://jasontrost.github.io"
echo "   (It may take a few minutes to deploy)"
echo ""
echo "5. To set up custom domain (jasontrost.com):"
echo "   - Add CNAME file (already included)"
echo "   - Update DNS settings at your domain registrar:"
echo "     - Add CNAME record: www -> jasontrost.github.io"
echo "     - Add A records for apex domain:"
echo "       185.199.108.153"
echo "       185.199.109.153"
echo "       185.199.110.153"
echo "       185.199.111.153"